class MyErr(def message: Str): Exception
class MyOtherErr(def message: Str): Exception

def function_may_throw_err() -> Int raise [MyErr] => 10

def g() =>
    def a := function_may_throw_err() handle
        err: MyErr =>
            print("We have a problem: {err.message}.")
            return  # we return, halting execution
        err: MyOtherErr =>
            print("We have another problem: {err.message}.")
            0  # ... or we assign default value 0 to a

    print("a has value {a}.")

g()
